version: '3.7'
services:
  gitlab:
    container_name: gitlab
    image: 'gitlab/gitlab-ce:16.6.2-ce.0'
    restart: always
    hostname: 'gitlab.local'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.local'
        gitlab_rails['gitlab_shell_ssh_port'] = 2424
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - '80:80'
      - '443:443'
      - '2424:22'
    volumes:
      - '/opt/gitlab/config:/etc/gitlab'
      - '/opt/gitlab/logs:/var/log/gitlab'
      - '/opt/gitlab/data:/var/opt/gitlab'

#  gitlab-runner:
#    container_name: gitlab-runner
#    image: gitlab/gitlab-runner:v16.6.2
#    restart: always
#    volumes:
#      - '/opt/gitlab-runner/config:/etc/gitlab-runner'
#      - '/var/run/docker.sock:/var/run/docker.sock:rw'
