stages:
  - repo-clone
  - bootstrap
  - cluster-ctrl
  - cluster-tune
  - deploy-infra
  - deploy-soft

repo-clone-job:
  stage: repo-clone
  tags:
    - kuber
  script:
    - cd ~
    - sudo rm -rf prowork
    - git clone https://github.com/slv-alt/prowork.git
    - echo "Clone Cfg project work directory complete."
    - sudo rm -rf kubespray
    - git clone https://github.com/slv-alt/kubespray.git
    - echo "Clone kubespray complete."

bootstrap-job:
  stage: bootstrap
  tags:
    - kuber
  script:
    - cd ~/kubespray
    - sudo ansible-playbook -i inventory/mycluster/hosts.yaml --become --become-user=root cluster.yml
    - echo "Cluster bootstrap complete."

cluster-ctrl-job:
  stage: cluster-ctrl
  tags:
    - kuber
  script:
    - sudo scp 192.168.1.31:/root/.kube/config /root/.kube/
    - sudo sed -i 's/127.0.0.1/192.168.1.31/' /root/.kube/config
    - echo "Take cluster control complete."

cluster-tune-job:
  stage: cluster-tune
  tags:
    - kuber
  script:
    - sudo ~/prowork/cluster-tune/tune.sh
    - cd ~/prowork/metallb
    - sudo ~/prowork/metallb/metallb.sh
    - echo "Tune cluster complete."

deploy-infra-job:
  stage: deploy-infra
  tags:
    - kuber
  script:
    - cd ~/prowork/deploy-infra
    - sudo ~/prowork/deploy-infra/deploy-infra.sh
    - echo "Deploy infra complete."

deploy-soft-job:
  stage: deploy-soft
  tags:
    - kuber
  script:
    - cd ~/prowork/deploy-soft
    - sudo ~/prowork/deploy-soft/deploy-soft.sh
    - echo "Deploy application Online Boutique complete."
