stages:          # List of stages for jobs, and their order of execution
  - build
  - bootstrap
  - cluster-tune

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  tags:
    - kuber
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."

bootstrap-job:
  stage: bootstrap
  tags:
    - kuber
  script:
    - sudo /home/gitlab-runner/cmd/bootstrap.sh
    - echo "Cluster bootstrap complete."
    
cluster-tune-job:
  stage: cluster-tune
  tags:
    - kuber
  script:
    - sudo scp 192.168.1.31:/root/.kube/config /root/.kube/
    - sudo sed -i 's/127.0.0.1/192.168.1.31/' /root/.kube/config
    - echo "Tune cluster complete."
